# Generated by Django 2.1.7 on 2019-04-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSetDetails',
        ),
    ]
