# Generated by Django 2.1.7 on 2019-05-04 05:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='category',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='sentiment',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
