# Generated by Django 2.1.7 on 2019-05-04 07:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190504_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='category',
            new_name='chartCategory',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='sentiment',
            new_name='sentimentCategory',
        ),
        migrations.AddField(
            model_name='result',
            name='sentimentProduct',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='sentimentSubcategory',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
