# Generated by Django 2.1.7 on 2019-05-05 09:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_result_chartsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='chartMonth',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='chartRegion',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
